// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsProbeHttp(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashProbeHttp(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsProbeHttp(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsProbeHttp(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsProbeHttp(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsProbeHttp(lhsKey, rhsKey) {
          if deepEqualsProbeHttp(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsProbeHttp(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashProbeHttp(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashProbeHttp(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashProbeHttp(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashProbeHttp(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashProbeHttp(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashProbeHttp(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum NativeProbeHttpErrorCode: Int {
  case invalidRequest = 0
  case sessionNotFound = 1
  case duplicateRequest = 2
  case cancelled = 3
  case timeout = 4
  case redirectRejected = 5
  case bodyTooLarge = 6
  case transportFailure = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeProbeHttpSession: Hashable {
  var sessionId: Int64
  var timeoutMilliseconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeProbeHttpSession? {
    let sessionId = pigeonVar_list[0] as! Int64
    let timeoutMilliseconds = pigeonVar_list[1] as! Int64

    return NativeProbeHttpSession(
      sessionId: sessionId,
      timeoutMilliseconds: timeoutMilliseconds
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      timeoutMilliseconds,
    ]
  }
  static func == (lhs: NativeProbeHttpSession, rhs: NativeProbeHttpSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsProbeHttp(lhs.sessionId, rhs.sessionId) && deepEqualsProbeHttp(lhs.timeoutMilliseconds, rhs.timeoutMilliseconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeProbeHttpSession")
    deepHashProbeHttp(value: sessionId, hasher: &hasher)
    deepHashProbeHttp(value: timeoutMilliseconds, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeProbeHttpRequest: Hashable {
  var sessionId: Int64
  var requestId: Int64
  var url: String
  var canonicalOrigin: String
  var headers: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeProbeHttpRequest? {
    let sessionId = pigeonVar_list[0] as! Int64
    let requestId = pigeonVar_list[1] as! Int64
    let url = pigeonVar_list[2] as! String
    let canonicalOrigin = pigeonVar_list[3] as! String
    let headers = pigeonVar_list[4] as! [String: String]

    return NativeProbeHttpRequest(
      sessionId: sessionId,
      requestId: requestId,
      url: url,
      canonicalOrigin: canonicalOrigin,
      headers: headers
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      requestId,
      url,
      canonicalOrigin,
      headers,
    ]
  }
  static func == (lhs: NativeProbeHttpRequest, rhs: NativeProbeHttpRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsProbeHttp(lhs.sessionId, rhs.sessionId) && deepEqualsProbeHttp(lhs.requestId, rhs.requestId) && deepEqualsProbeHttp(lhs.url, rhs.url) && deepEqualsProbeHttp(lhs.canonicalOrigin, rhs.canonicalOrigin) && deepEqualsProbeHttp(lhs.headers, rhs.headers)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeProbeHttpRequest")
    deepHashProbeHttp(value: sessionId, hasher: &hasher)
    deepHashProbeHttp(value: requestId, hasher: &hasher)
    deepHashProbeHttp(value: url, hasher: &hasher)
    deepHashProbeHttp(value: canonicalOrigin, hasher: &hasher)
    deepHashProbeHttp(value: headers, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeProbeHttpResponse: Hashable {
  var requestUrl: String
  var effectiveUrl: String
  var statusCode: Int64
  var body: String
  var redirectChain: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeProbeHttpResponse? {
    let requestUrl = pigeonVar_list[0] as! String
    let effectiveUrl = pigeonVar_list[1] as! String
    let statusCode = pigeonVar_list[2] as! Int64
    let body = pigeonVar_list[3] as! String
    let redirectChain = pigeonVar_list[4] as! [String]

    return NativeProbeHttpResponse(
      requestUrl: requestUrl,
      effectiveUrl: effectiveUrl,
      statusCode: statusCode,
      body: body,
      redirectChain: redirectChain
    )
  }
  func toList() -> [Any?] {
    return [
      requestUrl,
      effectiveUrl,
      statusCode,
      body,
      redirectChain,
    ]
  }
  static func == (lhs: NativeProbeHttpResponse, rhs: NativeProbeHttpResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsProbeHttp(lhs.requestUrl, rhs.requestUrl) && deepEqualsProbeHttp(lhs.effectiveUrl, rhs.effectiveUrl) && deepEqualsProbeHttp(lhs.statusCode, rhs.statusCode) && deepEqualsProbeHttp(lhs.body, rhs.body) && deepEqualsProbeHttp(lhs.redirectChain, rhs.redirectChain)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeProbeHttpResponse")
    deepHashProbeHttp(value: requestUrl, hasher: &hasher)
    deepHashProbeHttp(value: effectiveUrl, hasher: &hasher)
    deepHashProbeHttp(value: statusCode, hasher: &hasher)
    deepHashProbeHttp(value: body, hasher: &hasher)
    deepHashProbeHttp(value: redirectChain, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeProbeHttpResult: Hashable {
  var response: NativeProbeHttpResponse? = nil
  var error: NativeProbeHttpErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeProbeHttpResult? {
    let response: NativeProbeHttpResponse? = nilOrValue(pigeonVar_list[0])
    let error: NativeProbeHttpErrorCode? = nilOrValue(pigeonVar_list[1])

    return NativeProbeHttpResult(
      response: response,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      response,
      error,
    ]
  }
  static func == (lhs: NativeProbeHttpResult, rhs: NativeProbeHttpResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsProbeHttp(lhs.response, rhs.response) && deepEqualsProbeHttp(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeProbeHttpResult")
    deepHashProbeHttp(value: response, hasher: &hasher)
    deepHashProbeHttp(value: error, hasher: &hasher)
  }
}

private class ProbeHttpPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeProbeHttpErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return NativeProbeHttpSession.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeProbeHttpRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeProbeHttpResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeProbeHttpResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ProbeHttpPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeProbeHttpErrorCode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeProbeHttpSession {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeProbeHttpRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeProbeHttpResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeProbeHttpResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ProbeHttpPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ProbeHttpPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ProbeHttpPigeonCodecWriter(data: data)
  }
}

class ProbeHttpPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ProbeHttpPigeonCodec(readerWriter: ProbeHttpPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ProbeHttpApi {
  func openSession(session: NativeProbeHttpSession) throws
  func get(request: NativeProbeHttpRequest, completion: @escaping (Result<NativeProbeHttpResult, Error>) -> Void)
  func cancelRequest(sessionId: Int64, requestId: Int64) throws
  func closeSession(sessionId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ProbeHttpApiSetup {
  static var codec: FlutterStandardMessageCodec { ProbeHttpPigeonCodec.shared }
  /// Sets up an instance of `ProbeHttpApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ProbeHttpApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.openSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionArg = args[0] as! NativeProbeHttpSession
        do {
          try api.openSession(session: sessionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openSessionChannel.setMessageHandler(nil)
    }
    let getChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.get\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeProbeHttpRequest
        api.get(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getChannel.setMessageHandler(nil)
    }
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let requestIdArg = args[1] as! Int64
        do {
          try api.cancelRequest(sessionId: sessionIdArg, requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.closeSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
  }
}
