// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class PerformancePigeonCodecReader: FlutterStandardReader {
}

private class PerformancePigeonCodecWriter: FlutterStandardWriter {
}

private class PerformancePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PerformancePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PerformancePigeonCodecWriter(data: data)
  }
}

class PerformancePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PerformancePigeonCodec(readerWriter: PerformancePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PerformanceApi {
  func timelineInteractive() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PerformanceApiSetup {
  static var codec: FlutterStandardMessageCodec { PerformancePigeonCodec.shared }
  /// Sets up an instance of `PerformanceApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PerformanceApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let timelineInteractiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.PerformanceApi.timelineInteractive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      timelineInteractiveChannel.setMessageHandler { _, reply in
        do {
          try api.timelineInteractive()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      timelineInteractiveChannel.setMessageHandler(nil)
    }
  }
}
