// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsOriginalExport(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashOriginalExport(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsOriginalExport(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsOriginalExport(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsOriginalExport(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsOriginalExport(lhsKey, rhsKey) {
          if deepEqualsOriginalExport(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsOriginalExport(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashOriginalExport(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashOriginalExport(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashOriginalExport(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashOriginalExport(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashOriginalExport(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashOriginalExport(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum OriginalExportPolicy: Int {
  case localOnly = 0
  case allowICloud = 1
}

enum OriginalExportSchemePolicy: Int {
  case httpsOnly = 0
  case explicitlyApprovedHttp = 1
  case registeredLocalHttp = 2
}

enum OriginalExportErrorCode: Int {
  case assetMissing = 0
  case mediaNotLocal = 1
  case iCloudUnavailable = 2
  case cancelled = 3
  case staleContext = 4
  case timeout = 5
  case unauthorized = 6
  case wrongServer = 7
  case serverUnavailable = 8
  case httpFailure = 9
  case storageUnavailable = 10
  case writeFailed = 11
  case cleanupFailed = 12
  case leaseNotFound = 13
  case platformUnsupported = 14
}

/// Generated class from Pigeon that represents data sent in messages.
struct LocalOriginalExportRequest: Hashable {
  var requestId: Int64
  var assetId: String
  var suggestedName: String
  var policy: OriginalExportPolicy


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocalOriginalExportRequest? {
    let requestId = pigeonVar_list[0] as! Int64
    let assetId = pigeonVar_list[1] as! String
    let suggestedName = pigeonVar_list[2] as! String
    let policy = pigeonVar_list[3] as! OriginalExportPolicy

    return LocalOriginalExportRequest(
      requestId: requestId,
      assetId: assetId,
      suggestedName: suggestedName,
      policy: policy
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      assetId,
      suggestedName,
      policy,
    ]
  }
  static func == (lhs: LocalOriginalExportRequest, rhs: LocalOriginalExportRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOriginalExport(lhs.requestId, rhs.requestId) && deepEqualsOriginalExport(lhs.assetId, rhs.assetId) && deepEqualsOriginalExport(lhs.suggestedName, rhs.suggestedName) && deepEqualsOriginalExport(lhs.policy, rhs.policy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocalOriginalExportRequest")
    deepHashOriginalExport(value: requestId, hasher: &hasher)
    deepHashOriginalExport(value: assetId, hasher: &hasher)
    deepHashOriginalExport(value: suggestedName, hasher: &hasher)
    deepHashOriginalExport(value: policy, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RemoteOriginalExportRequest: Hashable {
  var requestId: Int64
  var url: String
  var origin: String
  var apiEndpoint: String
  var sessionEpoch: Int64
  var expectedContextGeneration: Int64
  var schemePolicy: OriginalExportSchemePolicy
  var suggestedName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RemoteOriginalExportRequest? {
    let requestId = pigeonVar_list[0] as! Int64
    let url = pigeonVar_list[1] as! String
    let origin = pigeonVar_list[2] as! String
    let apiEndpoint = pigeonVar_list[3] as! String
    let sessionEpoch = pigeonVar_list[4] as! Int64
    let expectedContextGeneration = pigeonVar_list[5] as! Int64
    let schemePolicy = pigeonVar_list[6] as! OriginalExportSchemePolicy
    let suggestedName = pigeonVar_list[7] as! String

    return RemoteOriginalExportRequest(
      requestId: requestId,
      url: url,
      origin: origin,
      apiEndpoint: apiEndpoint,
      sessionEpoch: sessionEpoch,
      expectedContextGeneration: expectedContextGeneration,
      schemePolicy: schemePolicy,
      suggestedName: suggestedName
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      url,
      origin,
      apiEndpoint,
      sessionEpoch,
      expectedContextGeneration,
      schemePolicy,
      suggestedName,
    ]
  }
  static func == (lhs: RemoteOriginalExportRequest, rhs: RemoteOriginalExportRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOriginalExport(lhs.requestId, rhs.requestId) && deepEqualsOriginalExport(lhs.url, rhs.url) && deepEqualsOriginalExport(lhs.origin, rhs.origin) && deepEqualsOriginalExport(lhs.apiEndpoint, rhs.apiEndpoint) && deepEqualsOriginalExport(lhs.sessionEpoch, rhs.sessionEpoch) && deepEqualsOriginalExport(lhs.expectedContextGeneration, rhs.expectedContextGeneration) && deepEqualsOriginalExport(lhs.schemePolicy, rhs.schemePolicy) && deepEqualsOriginalExport(lhs.suggestedName, rhs.suggestedName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RemoteOriginalExportRequest")
    deepHashOriginalExport(value: requestId, hasher: &hasher)
    deepHashOriginalExport(value: url, hasher: &hasher)
    deepHashOriginalExport(value: origin, hasher: &hasher)
    deepHashOriginalExport(value: apiEndpoint, hasher: &hasher)
    deepHashOriginalExport(value: sessionEpoch, hasher: &hasher)
    deepHashOriginalExport(value: expectedContextGeneration, hasher: &hasher)
    deepHashOriginalExport(value: schemePolicy, hasher: &hasher)
    deepHashOriginalExport(value: suggestedName, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OriginalExportResult: Hashable {
  var path: String? = nil
  var leaseToken: String? = nil
  var error: OriginalExportErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OriginalExportResult? {
    let path: String? = nilOrValue(pigeonVar_list[0])
    let leaseToken: String? = nilOrValue(pigeonVar_list[1])
    let error: OriginalExportErrorCode? = nilOrValue(pigeonVar_list[2])

    return OriginalExportResult(
      path: path,
      leaseToken: leaseToken,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      leaseToken,
      error,
    ]
  }
  static func == (lhs: OriginalExportResult, rhs: OriginalExportResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOriginalExport(lhs.path, rhs.path) && deepEqualsOriginalExport(lhs.leaseToken, rhs.leaseToken) && deepEqualsOriginalExport(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OriginalExportResult")
    deepHashOriginalExport(value: path, hasher: &hasher)
    deepHashOriginalExport(value: leaseToken, hasher: &hasher)
    deepHashOriginalExport(value: error, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OriginalExportReleaseResult: Hashable {
  var error: OriginalExportErrorCode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OriginalExportReleaseResult? {
    let error: OriginalExportErrorCode? = nilOrValue(pigeonVar_list[0])

    return OriginalExportReleaseResult(
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      error
    ]
  }
  static func == (lhs: OriginalExportReleaseResult, rhs: OriginalExportReleaseResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOriginalExport(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OriginalExportReleaseResult")
    deepHashOriginalExport(value: error, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OriginalExportProgress: Hashable {
  var requestId: Int64
  var fraction: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OriginalExportProgress? {
    let requestId = pigeonVar_list[0] as! Int64
    let fraction = pigeonVar_list[1] as! Double

    return OriginalExportProgress(
      requestId: requestId,
      fraction: fraction
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      fraction,
    ]
  }
  static func == (lhs: OriginalExportProgress, rhs: OriginalExportProgress) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsOriginalExport(lhs.requestId, rhs.requestId) && deepEqualsOriginalExport(lhs.fraction, rhs.fraction)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OriginalExportProgress")
    deepHashOriginalExport(value: requestId, hasher: &hasher)
    deepHashOriginalExport(value: fraction, hasher: &hasher)
  }
}

private class OriginalExportPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OriginalExportPolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OriginalExportSchemePolicy(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OriginalExportErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return LocalOriginalExportRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return RemoteOriginalExportRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return OriginalExportResult.fromList(self.readValue() as! [Any?])
    case 135:
      return OriginalExportReleaseResult.fromList(self.readValue() as! [Any?])
    case 136:
      return OriginalExportProgress.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class OriginalExportPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OriginalExportPolicy {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? OriginalExportSchemePolicy {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? OriginalExportErrorCode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocalOriginalExportRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? RemoteOriginalExportRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? OriginalExportResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? OriginalExportReleaseResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? OriginalExportProgress {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class OriginalExportPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OriginalExportPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OriginalExportPigeonCodecWriter(data: data)
  }
}

class OriginalExportPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OriginalExportPigeonCodec(readerWriter: OriginalExportPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OriginalExportApi {
  func exportLocal(request: LocalOriginalExportRequest, completion: @escaping (Result<OriginalExportResult, Error>) -> Void)
  func exportRemote(request: RemoteOriginalExportRequest, completion: @escaping (Result<OriginalExportResult, Error>) -> Void)
  func cancelRequest(requestId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelAll(completion: @escaping (Result<Void, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
  func releaseLease(leaseToken: String, completion: @escaping (Result<OriginalExportReleaseResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OriginalExportApiSetup {
  static var codec: FlutterStandardMessageCodec { OriginalExportPigeonCodec.shared }
  /// Sets up an instance of `OriginalExportApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OriginalExportApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let exportLocalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportLocal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportLocalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LocalOriginalExportRequest
        api.exportLocal(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportLocalChannel.setMessageHandler(nil)
    }
    let exportRemoteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportRemote\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportRemoteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RemoteOriginalExportRequest
        api.exportRemote(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportRemoteChannel.setMessageHandler(nil)
    }
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        api.cancelRequest(requestId: requestIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        api.cancelAll { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let releaseLeaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.OriginalExportApi.releaseLease\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseLeaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let leaseTokenArg = args[0] as! String
        api.releaseLease(leaseToken: leaseTokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseLeaseChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol OriginalExportFlutterApiProtocol {
  func onProgress(progress progressArg: OriginalExportProgress, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class OriginalExportFlutterApi: OriginalExportFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: OriginalExportPigeonCodec {
    return OriginalExportPigeonCodec.shared
  }
  func onProgress(progress progressArg: OriginalExportProgress, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.OriginalExportFlutterApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
