// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.alextran.immich.core

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ProbeHttpPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class NativeProbeHttpErrorCode(val raw: Int) {
  INVALID_REQUEST(0),
  SESSION_NOT_FOUND(1),
  DUPLICATE_REQUEST(2),
  CANCELLED(3),
  TIMEOUT(4),
  REDIRECT_REJECTED(5),
  BODY_TOO_LARGE(6),
  TRANSPORT_FAILURE(7);

  companion object {
    fun ofRaw(raw: Int): NativeProbeHttpErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeProbeHttpSession (
  val sessionId: Long,
  val timeoutMilliseconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeProbeHttpSession {
      val sessionId = pigeonVar_list[0] as Long
      val timeoutMilliseconds = pigeonVar_list[1] as Long
      return NativeProbeHttpSession(sessionId, timeoutMilliseconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      timeoutMilliseconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeProbeHttpSession
    return ProbeHttpPigeonUtils.deepEquals(this.sessionId, other.sessionId) && ProbeHttpPigeonUtils.deepEquals(this.timeoutMilliseconds, other.timeoutMilliseconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.timeoutMilliseconds)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeProbeHttpRequest (
  val sessionId: Long,
  val requestId: Long,
  val url: String,
  val canonicalOrigin: String,
  val headers: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeProbeHttpRequest {
      val sessionId = pigeonVar_list[0] as Long
      val requestId = pigeonVar_list[1] as Long
      val url = pigeonVar_list[2] as String
      val canonicalOrigin = pigeonVar_list[3] as String
      val headers = pigeonVar_list[4] as Map<String, String>
      return NativeProbeHttpRequest(sessionId, requestId, url, canonicalOrigin, headers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      requestId,
      url,
      canonicalOrigin,
      headers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeProbeHttpRequest
    return ProbeHttpPigeonUtils.deepEquals(this.sessionId, other.sessionId) && ProbeHttpPigeonUtils.deepEquals(this.requestId, other.requestId) && ProbeHttpPigeonUtils.deepEquals(this.url, other.url) && ProbeHttpPigeonUtils.deepEquals(this.canonicalOrigin, other.canonicalOrigin) && ProbeHttpPigeonUtils.deepEquals(this.headers, other.headers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.requestId)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.url)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.canonicalOrigin)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.headers)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeProbeHttpResponse (
  val requestUrl: String,
  val effectiveUrl: String,
  val statusCode: Long,
  val body: String,
  val redirectChain: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeProbeHttpResponse {
      val requestUrl = pigeonVar_list[0] as String
      val effectiveUrl = pigeonVar_list[1] as String
      val statusCode = pigeonVar_list[2] as Long
      val body = pigeonVar_list[3] as String
      val redirectChain = pigeonVar_list[4] as List<String>
      return NativeProbeHttpResponse(requestUrl, effectiveUrl, statusCode, body, redirectChain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestUrl,
      effectiveUrl,
      statusCode,
      body,
      redirectChain,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeProbeHttpResponse
    return ProbeHttpPigeonUtils.deepEquals(this.requestUrl, other.requestUrl) && ProbeHttpPigeonUtils.deepEquals(this.effectiveUrl, other.effectiveUrl) && ProbeHttpPigeonUtils.deepEquals(this.statusCode, other.statusCode) && ProbeHttpPigeonUtils.deepEquals(this.body, other.body) && ProbeHttpPigeonUtils.deepEquals(this.redirectChain, other.redirectChain)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.requestUrl)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.effectiveUrl)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.statusCode)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.body)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.redirectChain)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeProbeHttpResult (
  val response: NativeProbeHttpResponse? = null,
  val error: NativeProbeHttpErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeProbeHttpResult {
      val response = pigeonVar_list[0] as NativeProbeHttpResponse?
      val error = pigeonVar_list[1] as NativeProbeHttpErrorCode?
      return NativeProbeHttpResult(response, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      response,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeProbeHttpResult
    return ProbeHttpPigeonUtils.deepEquals(this.response, other.response) && ProbeHttpPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.response)
    result = 31 * result + ProbeHttpPigeonUtils.deepHash(this.error)
    return result
  }
}
private open class ProbeHttpPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeProbeHttpErrorCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeProbeHttpSession.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeProbeHttpRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeProbeHttpResponse.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeProbeHttpResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeProbeHttpErrorCode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeProbeHttpSession -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeProbeHttpRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeProbeHttpResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeProbeHttpResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProbeHttpApi {
  fun openSession(session: NativeProbeHttpSession)
  fun get(request: NativeProbeHttpRequest, callback: (Result<NativeProbeHttpResult>) -> Unit)
  fun cancelRequest(sessionId: Long, requestId: Long)
  fun closeSession(sessionId: Long)

  companion object {
    /** The codec used by ProbeHttpApi. */
    val codec: MessageCodec<Any?> by lazy {
      ProbeHttpPigeonCodec()
    }
    /** Sets up an instance of `ProbeHttpApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProbeHttpApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.openSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionArg = args[0] as NativeProbeHttpSession
            val wrapped: List<Any?> = try {
              api.openSession(sessionArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProbeHttpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.get$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeProbeHttpRequest
            api.get(requestArg) { result: Result<NativeProbeHttpResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProbeHttpPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProbeHttpPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val requestIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(sessionIdArg, requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProbeHttpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.ProbeHttpApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.closeSession(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              ProbeHttpPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
