// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.alextran.immich.share

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object OriginalExportPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class OriginalExportPolicy(val raw: Int) {
  LOCAL_ONLY(0),
  ALLOW_ICLOUD(1);

  companion object {
    fun ofRaw(raw: Int): OriginalExportPolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class OriginalExportSchemePolicy(val raw: Int) {
  HTTPS_ONLY(0),
  EXPLICITLY_APPROVED_HTTP(1),
  REGISTERED_LOCAL_HTTP(2);

  companion object {
    fun ofRaw(raw: Int): OriginalExportSchemePolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class OriginalExportErrorCode(val raw: Int) {
  ASSET_MISSING(0),
  MEDIA_NOT_LOCAL(1),
  I_CLOUD_UNAVAILABLE(2),
  CANCELLED(3),
  STALE_CONTEXT(4),
  TIMEOUT(5),
  UNAUTHORIZED(6),
  WRONG_SERVER(7),
  SERVER_UNAVAILABLE(8),
  HTTP_FAILURE(9),
  STORAGE_UNAVAILABLE(10),
  WRITE_FAILED(11),
  CLEANUP_FAILED(12),
  LEASE_NOT_FOUND(13),
  PLATFORM_UNSUPPORTED(14);

  companion object {
    fun ofRaw(raw: Int): OriginalExportErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalOriginalExportRequest (
  val requestId: Long,
  val assetId: String,
  val suggestedName: String,
  val policy: OriginalExportPolicy
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalOriginalExportRequest {
      val requestId = pigeonVar_list[0] as Long
      val assetId = pigeonVar_list[1] as String
      val suggestedName = pigeonVar_list[2] as String
      val policy = pigeonVar_list[3] as OriginalExportPolicy
      return LocalOriginalExportRequest(requestId, assetId, suggestedName, policy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      assetId,
      suggestedName,
      policy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalOriginalExportRequest
    return OriginalExportPigeonUtils.deepEquals(this.requestId, other.requestId) && OriginalExportPigeonUtils.deepEquals(this.assetId, other.assetId) && OriginalExportPigeonUtils.deepEquals(this.suggestedName, other.suggestedName) && OriginalExportPigeonUtils.deepEquals(this.policy, other.policy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.requestId)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.assetId)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.suggestedName)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.policy)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemoteOriginalExportRequest (
  val requestId: Long,
  val url: String,
  val origin: String,
  val apiEndpoint: String,
  val sessionEpoch: Long,
  val expectedContextGeneration: Long,
  val schemePolicy: OriginalExportSchemePolicy,
  val suggestedName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteOriginalExportRequest {
      val requestId = pigeonVar_list[0] as Long
      val url = pigeonVar_list[1] as String
      val origin = pigeonVar_list[2] as String
      val apiEndpoint = pigeonVar_list[3] as String
      val sessionEpoch = pigeonVar_list[4] as Long
      val expectedContextGeneration = pigeonVar_list[5] as Long
      val schemePolicy = pigeonVar_list[6] as OriginalExportSchemePolicy
      val suggestedName = pigeonVar_list[7] as String
      return RemoteOriginalExportRequest(requestId, url, origin, apiEndpoint, sessionEpoch, expectedContextGeneration, schemePolicy, suggestedName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      url,
      origin,
      apiEndpoint,
      sessionEpoch,
      expectedContextGeneration,
      schemePolicy,
      suggestedName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteOriginalExportRequest
    return OriginalExportPigeonUtils.deepEquals(this.requestId, other.requestId) && OriginalExportPigeonUtils.deepEquals(this.url, other.url) && OriginalExportPigeonUtils.deepEquals(this.origin, other.origin) && OriginalExportPigeonUtils.deepEquals(this.apiEndpoint, other.apiEndpoint) && OriginalExportPigeonUtils.deepEquals(this.sessionEpoch, other.sessionEpoch) && OriginalExportPigeonUtils.deepEquals(this.expectedContextGeneration, other.expectedContextGeneration) && OriginalExportPigeonUtils.deepEquals(this.schemePolicy, other.schemePolicy) && OriginalExportPigeonUtils.deepEquals(this.suggestedName, other.suggestedName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.requestId)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.url)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.origin)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.apiEndpoint)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.sessionEpoch)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.expectedContextGeneration)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.schemePolicy)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.suggestedName)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OriginalExportResult (
  val path: String? = null,
  val leaseToken: String? = null,
  val error: OriginalExportErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OriginalExportResult {
      val path = pigeonVar_list[0] as String?
      val leaseToken = pigeonVar_list[1] as String?
      val error = pigeonVar_list[2] as OriginalExportErrorCode?
      return OriginalExportResult(path, leaseToken, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      leaseToken,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OriginalExportResult
    return OriginalExportPigeonUtils.deepEquals(this.path, other.path) && OriginalExportPigeonUtils.deepEquals(this.leaseToken, other.leaseToken) && OriginalExportPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.path)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.leaseToken)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.error)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OriginalExportReleaseResult (
  val error: OriginalExportErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OriginalExportReleaseResult {
      val error = pigeonVar_list[0] as OriginalExportErrorCode?
      return OriginalExportReleaseResult(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OriginalExportReleaseResult
    return OriginalExportPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.error)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OriginalExportProgress (
  val requestId: Long,
  val fraction: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OriginalExportProgress {
      val requestId = pigeonVar_list[0] as Long
      val fraction = pigeonVar_list[1] as Double
      return OriginalExportProgress(requestId, fraction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      fraction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OriginalExportProgress
    return OriginalExportPigeonUtils.deepEquals(this.requestId, other.requestId) && OriginalExportPigeonUtils.deepEquals(this.fraction, other.fraction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.requestId)
    result = 31 * result + OriginalExportPigeonUtils.deepHash(this.fraction)
    return result
  }
}
private open class OriginalExportPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OriginalExportPolicy.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OriginalExportSchemePolicy.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OriginalExportErrorCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalOriginalExportRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteOriginalExportRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OriginalExportResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OriginalExportReleaseResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OriginalExportProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OriginalExportPolicy -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is OriginalExportSchemePolicy -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is OriginalExportErrorCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is LocalOriginalExportRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is RemoteOriginalExportRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is OriginalExportResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is OriginalExportReleaseResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is OriginalExportProgress -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OriginalExportApi {
  fun exportLocal(request: LocalOriginalExportRequest, callback: (Result<OriginalExportResult>) -> Unit)
  fun exportRemote(request: RemoteOriginalExportRequest, callback: (Result<OriginalExportResult>) -> Unit)
  fun cancelRequest(requestId: Long, callback: (Result<Unit>) -> Unit)
  fun cancelAll(callback: (Result<Unit>) -> Unit)
  fun dispose(callback: (Result<Unit>) -> Unit)
  fun releaseLease(leaseToken: String, callback: (Result<OriginalExportReleaseResult>) -> Unit)

  companion object {
    /** The codec used by OriginalExportApi. */
    val codec: MessageCodec<Any?> by lazy {
      OriginalExportPigeonCodec()
    }
    /** Sets up an instance of `OriginalExportApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OriginalExportApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportLocal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LocalOriginalExportRequest
            api.exportLocal(requestArg) { result: Result<OriginalExportResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OriginalExportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportRemote$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RemoteOriginalExportRequest
            api.exportRemote(requestArg) { result: Result<OriginalExportResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OriginalExportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            api.cancelRequest(requestIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                reply.reply(OriginalExportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelAll{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                reply.reply(OriginalExportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                reply.reply(OriginalExportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.OriginalExportApi.releaseLease$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseTokenArg = args[0] as String
            api.releaseLease(leaseTokenArg) { result: Result<OriginalExportReleaseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(OriginalExportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(OriginalExportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class OriginalExportFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by OriginalExportFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      OriginalExportPigeonCodec()
    }
  }
  fun onProgress(progressArg: OriginalExportProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.immich_mobile.OriginalExportFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(OriginalExportPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
