// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(List<Object?>? replyList, String channelName, {required bool isNullValid}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum OriginalExportPolicy { localOnly, allowICloud }

enum OriginalExportErrorCode {
  assetMissing,
  mediaNotLocal,
  iCloudUnavailable,
  cancelled,
  timeout,
  unauthorized,
  wrongServer,
  serverUnavailable,
  httpFailure,
  storageUnavailable,
  writeFailed,
  cleanupFailed,
  leaseNotFound,
  platformUnsupported,
}

class LocalOriginalExportRequest {
  LocalOriginalExportRequest({
    required this.requestId,
    required this.assetId,
    required this.suggestedName,
    required this.policy,
  });

  int requestId;

  String assetId;

  String suggestedName;

  OriginalExportPolicy policy;

  List<Object?> _toList() {
    return <Object?>[requestId, assetId, suggestedName, policy];
  }

  Object encode() {
    return _toList();
  }

  static LocalOriginalExportRequest decode(Object result) {
    result as List<Object?>;
    return LocalOriginalExportRequest(
      requestId: result[0]! as int,
      assetId: result[1]! as String,
      suggestedName: result[2]! as String,
      policy: result[3]! as OriginalExportPolicy,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalOriginalExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(assetId, other.assetId) &&
        _deepEquals(suggestedName, other.suggestedName) &&
        _deepEquals(policy, other.policy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class RemoteOriginalExportRequest {
  RemoteOriginalExportRequest({
    required this.requestId,
    required this.url,
    required this.origin,
    required this.suggestedName,
  });

  int requestId;

  String url;

  String origin;

  String suggestedName;

  List<Object?> _toList() {
    return <Object?>[requestId, url, origin, suggestedName];
  }

  Object encode() {
    return _toList();
  }

  static RemoteOriginalExportRequest decode(Object result) {
    result as List<Object?>;
    return RemoteOriginalExportRequest(
      requestId: result[0]! as int,
      url: result[1]! as String,
      origin: result[2]! as String,
      suggestedName: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RemoteOriginalExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(url, other.url) &&
        _deepEquals(origin, other.origin) &&
        _deepEquals(suggestedName, other.suggestedName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class OriginalExportResult {
  OriginalExportResult({this.path, this.leaseToken, this.error});

  String? path;

  String? leaseToken;

  OriginalExportErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[path, leaseToken, error];
  }

  Object encode() {
    return _toList();
  }

  static OriginalExportResult decode(Object result) {
    result as List<Object?>;
    return OriginalExportResult(
      path: result[0] as String?,
      leaseToken: result[1] as String?,
      error: result[2] as OriginalExportErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OriginalExportResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(leaseToken, other.leaseToken) &&
        _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class OriginalExportReleaseResult {
  OriginalExportReleaseResult({this.error});

  OriginalExportErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static OriginalExportReleaseResult decode(Object result) {
    result as List<Object?>;
    return OriginalExportReleaseResult(error: result[0] as OriginalExportErrorCode?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OriginalExportReleaseResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class OriginalExportProgress {
  OriginalExportProgress({required this.requestId, required this.fraction});

  int requestId;

  double fraction;

  List<Object?> _toList() {
    return <Object?>[requestId, fraction];
  }

  Object encode() {
    return _toList();
  }

  static OriginalExportProgress decode(Object result) {
    result as List<Object?>;
    return OriginalExportProgress(requestId: result[0]! as int, fraction: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OriginalExportProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) && _deepEquals(fraction, other.fraction);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is OriginalExportPolicy) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is OriginalExportErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is LocalOriginalExportRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RemoteOriginalExportRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is OriginalExportResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is OriginalExportReleaseResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is OriginalExportProgress) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : OriginalExportPolicy.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : OriginalExportErrorCode.values[value];
      case 131:
        return LocalOriginalExportRequest.decode(readValue(buffer)!);
      case 132:
        return RemoteOriginalExportRequest.decode(readValue(buffer)!);
      case 133:
        return OriginalExportResult.decode(readValue(buffer)!);
      case 134:
        return OriginalExportReleaseResult.decode(readValue(buffer)!);
      case 135:
        return OriginalExportProgress.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OriginalExportApi {
  /// Constructor for [OriginalExportApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OriginalExportApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<OriginalExportResult> exportLocal(LocalOriginalExportRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportLocal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OriginalExportResult;
  }

  Future<OriginalExportResult> exportRemote(RemoteOriginalExportRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.exportRemote$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OriginalExportResult;
  }

  Future<void> cancelRequest(int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[requestId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> cancelAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> dispose() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<OriginalExportReleaseResult> releaseLease(String leaseToken) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.OriginalExportApi.releaseLease$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[leaseToken]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OriginalExportReleaseResult;
  }
}

abstract class OriginalExportFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(OriginalExportProgress progress);

  static void setUp(
    OriginalExportFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.immich_mobile.OriginalExportFlutterApi.onProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final OriginalExportProgress arg_progress = args[0]! as OriginalExportProgress;
          try {
            api.onProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
