// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(List<Object?>? replyList, String channelName, {required bool isNullValid}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum NativeProbeHttpErrorCode {
  invalidRequest,
  sessionNotFound,
  duplicateRequest,
  cancelled,
  timeout,
  redirectRejected,
  bodyTooLarge,
  transportFailure,
}

class NativeProbeHttpSession {
  NativeProbeHttpSession({required this.sessionId, required this.timeoutMilliseconds});

  int sessionId;

  int timeoutMilliseconds;

  List<Object?> _toList() {
    return <Object?>[sessionId, timeoutMilliseconds];
  }

  Object encode() {
    return _toList();
  }

  static NativeProbeHttpSession decode(Object result) {
    result as List<Object?>;
    return NativeProbeHttpSession(sessionId: result[0]! as int, timeoutMilliseconds: result[1]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeProbeHttpSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(timeoutMilliseconds, other.timeoutMilliseconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeProbeHttpRequest {
  NativeProbeHttpRequest({
    required this.sessionId,
    required this.requestId,
    required this.url,
    required this.canonicalOrigin,
    required this.headers,
  });

  int sessionId;

  int requestId;

  String url;

  String canonicalOrigin;

  Map<String, String> headers;

  List<Object?> _toList() {
    return <Object?>[sessionId, requestId, url, canonicalOrigin, headers];
  }

  Object encode() {
    return _toList();
  }

  static NativeProbeHttpRequest decode(Object result) {
    result as List<Object?>;
    return NativeProbeHttpRequest(
      sessionId: result[0]! as int,
      requestId: result[1]! as int,
      url: result[2]! as String,
      canonicalOrigin: result[3]! as String,
      headers: (result[4]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeProbeHttpRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) &&
        _deepEquals(requestId, other.requestId) &&
        _deepEquals(url, other.url) &&
        _deepEquals(canonicalOrigin, other.canonicalOrigin) &&
        _deepEquals(headers, other.headers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeProbeHttpResponse {
  NativeProbeHttpResponse({
    required this.requestUrl,
    required this.effectiveUrl,
    required this.statusCode,
    required this.body,
    required this.redirectChain,
  });

  String requestUrl;

  String effectiveUrl;

  int statusCode;

  String body;

  List<String> redirectChain;

  List<Object?> _toList() {
    return <Object?>[requestUrl, effectiveUrl, statusCode, body, redirectChain];
  }

  Object encode() {
    return _toList();
  }

  static NativeProbeHttpResponse decode(Object result) {
    result as List<Object?>;
    return NativeProbeHttpResponse(
      requestUrl: result[0]! as String,
      effectiveUrl: result[1]! as String,
      statusCode: result[2]! as int,
      body: result[3]! as String,
      redirectChain: (result[4]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeProbeHttpResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestUrl, other.requestUrl) &&
        _deepEquals(effectiveUrl, other.effectiveUrl) &&
        _deepEquals(statusCode, other.statusCode) &&
        _deepEquals(body, other.body) &&
        _deepEquals(redirectChain, other.redirectChain);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class NativeProbeHttpResult {
  NativeProbeHttpResult({this.response, this.error});

  NativeProbeHttpResponse? response;

  NativeProbeHttpErrorCode? error;

  List<Object?> _toList() {
    return <Object?>[response, error];
  }

  Object encode() {
    return _toList();
  }

  static NativeProbeHttpResult decode(Object result) {
    result as List<Object?>;
    return NativeProbeHttpResult(
      response: result[0] as NativeProbeHttpResponse?,
      error: result[1] as NativeProbeHttpErrorCode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeProbeHttpResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(response, other.response) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeProbeHttpErrorCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NativeProbeHttpSession) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeProbeHttpRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeProbeHttpResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is NativeProbeHttpResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeProbeHttpErrorCode.values[value];
      case 130:
        return NativeProbeHttpSession.decode(readValue(buffer)!);
      case 131:
        return NativeProbeHttpRequest.decode(readValue(buffer)!);
      case 132:
        return NativeProbeHttpResponse.decode(readValue(buffer)!);
      case 133:
        return NativeProbeHttpResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ProbeHttpApi {
  /// Constructor for [ProbeHttpApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ProbeHttpApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> openSession(NativeProbeHttpSession session) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.ProbeHttpApi.openSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[session]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<NativeProbeHttpResult> get(NativeProbeHttpRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.ProbeHttpApi.get$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeProbeHttpResult;
  }

  Future<void> cancelRequest(int sessionId, int requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.ProbeHttpApi.cancelRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, requestId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  Future<void> closeSession(int sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.immich_mobile.ProbeHttpApi.closeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }
}
