// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.alextran.immich.images

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LocalImagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class LocalImagePolicy(val raw: Int) {
  LOCAL_ONLY(0),
  ALLOW_ICLOUD(1);

  companion object {
    fun ofRaw(raw: Int): LocalImagePolicy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LocalImageRequestKind(val raw: Int) {
  THUMBNAIL(0),
  ORIGINAL(1);

  companion object {
    fun ofRaw(raw: Int): LocalImageRequestKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LocalImageErrorCode(val raw: Int) {
  CACHE_MISS(0),
  MEDIA_NOT_LOCAL(1),
  I_CLOUD_UNAVAILABLE(2),
  CANCELLED(3),
  TIMEOUT(4),
  SERVER_UNAVAILABLE(5),
  WRONG_SERVER(6),
  UNAUTHORIZED(7);

  companion object {
    fun ofRaw(raw: Int): LocalImageErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalImageRequest (
  val assetId: String,
  val requestId: Long,
  val width: Long,
  val height: Long,
  val isVideo: Boolean,
  val preferEncoded: Boolean,
  val policy: LocalImagePolicy,
  val kind: LocalImageRequestKind
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalImageRequest {
      val assetId = pigeonVar_list[0] as String
      val requestId = pigeonVar_list[1] as Long
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val isVideo = pigeonVar_list[4] as Boolean
      val preferEncoded = pigeonVar_list[5] as Boolean
      val policy = pigeonVar_list[6] as LocalImagePolicy
      val kind = pigeonVar_list[7] as LocalImageRequestKind
      return LocalImageRequest(assetId, requestId, width, height, isVideo, preferEncoded, policy, kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      assetId,
      requestId,
      width,
      height,
      isVideo,
      preferEncoded,
      policy,
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalImageRequest
    return LocalImagesPigeonUtils.deepEquals(this.assetId, other.assetId) && LocalImagesPigeonUtils.deepEquals(this.requestId, other.requestId) && LocalImagesPigeonUtils.deepEquals(this.width, other.width) && LocalImagesPigeonUtils.deepEquals(this.height, other.height) && LocalImagesPigeonUtils.deepEquals(this.isVideo, other.isVideo) && LocalImagesPigeonUtils.deepEquals(this.preferEncoded, other.preferEncoded) && LocalImagesPigeonUtils.deepEquals(this.policy, other.policy) && LocalImagesPigeonUtils.deepEquals(this.kind, other.kind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.assetId)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.width)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.height)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.isVideo)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.preferEncoded)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.policy)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.kind)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalImageThumbhashRequest (
  val thumbhash: String,
  val requestId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalImageThumbhashRequest {
      val thumbhash = pigeonVar_list[0] as String
      val requestId = pigeonVar_list[1] as Long
      return LocalImageThumbhashRequest(thumbhash, requestId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      thumbhash,
      requestId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalImageThumbhashRequest
    return LocalImagesPigeonUtils.deepEquals(this.thumbhash, other.thumbhash) && LocalImagesPigeonUtils.deepEquals(this.requestId, other.requestId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.thumbhash)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.requestId)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalImagePayload (
  val pointer: Long,
  val length: Long? = null,
  val width: Long? = null,
  val height: Long? = null,
  val rowBytes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalImagePayload {
      val pointer = pigeonVar_list[0] as Long
      val length = pigeonVar_list[1] as Long?
      val width = pigeonVar_list[2] as Long?
      val height = pigeonVar_list[3] as Long?
      val rowBytes = pigeonVar_list[4] as Long?
      return LocalImagePayload(pointer, length, width, height, rowBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pointer,
      length,
      width,
      height,
      rowBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalImagePayload
    return LocalImagesPigeonUtils.deepEquals(this.pointer, other.pointer) && LocalImagesPigeonUtils.deepEquals(this.length, other.length) && LocalImagesPigeonUtils.deepEquals(this.width, other.width) && LocalImagesPigeonUtils.deepEquals(this.height, other.height) && LocalImagesPigeonUtils.deepEquals(this.rowBytes, other.rowBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.pointer)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.length)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.width)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.height)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.rowBytes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalImageResult (
  val payload: LocalImagePayload? = null,
  val error: LocalImageErrorCode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalImageResult {
      val payload = pigeonVar_list[0] as LocalImagePayload?
      val error = pigeonVar_list[1] as LocalImageErrorCode?
      return LocalImageResult(payload, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      payload,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalImageResult
    return LocalImagesPigeonUtils.deepEquals(this.payload, other.payload) && LocalImagesPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.payload)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.error)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalImageProgress (
  val requestId: Long,
  val fraction: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalImageProgress {
      val requestId = pigeonVar_list[0] as Long
      val fraction = pigeonVar_list[1] as Double
      return LocalImageProgress(requestId, fraction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      fraction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocalImageProgress
    return LocalImagesPigeonUtils.deepEquals(this.requestId, other.requestId) && LocalImagesPigeonUtils.deepEquals(this.fraction, other.fraction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.requestId)
    result = 31 * result + LocalImagesPigeonUtils.deepHash(this.fraction)
    return result
  }
}
private open class LocalImagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocalImagePolicy.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocalImageRequestKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocalImageErrorCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalImageRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalImageThumbhashRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalImagePayload.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalImageResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalImageProgress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LocalImagePolicy -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is LocalImageRequestKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is LocalImageErrorCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is LocalImageRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LocalImageThumbhashRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is LocalImagePayload -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is LocalImageResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is LocalImageProgress -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocalImageApi {
  fun requestImage(request: LocalImageRequest, callback: (Result<LocalImageResult>) -> Unit)
  fun cancelRequest(requestId: Long)
  fun cancelAll()
  fun dispose()
  fun getThumbhash(request: LocalImageThumbhashRequest, callback: (Result<LocalImageResult>) -> Unit)

  companion object {
    /** The codec used by LocalImageApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocalImagesPigeonCodec()
    }
    /** Sets up an instance of `LocalImageApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocalImageApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.LocalImageApi.requestImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LocalImageRequest
            api.requestImage(requestArg) { result: Result<LocalImageResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalImagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalImagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.LocalImageApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocalImagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.LocalImageApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelAll()
              listOf(null)
            } catch (exception: Throwable) {
              LocalImagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.LocalImageApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.dispose()
              listOf(null)
            } catch (exception: Throwable) {
              LocalImagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.LocalImageApi.getThumbhash$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LocalImageThumbhashRequest
            api.getThumbhash(requestArg) { result: Result<LocalImageResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocalImagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocalImagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LocalImageFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LocalImageFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocalImagesPigeonCodec()
    }
  }
  fun onProgress(progressArg: LocalImageProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.immich_mobile.LocalImageFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LocalImagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
